const DEFAULT_WS_ACCESS_PARAM = 'access';
const DEFAULT_HTTP_ACCESS_HEADER = 'x-authorization';
const DEFAULT_URL_ACCESS_PARAM = 'access';
const DEFAULT_BROWSER_STORAGE_KEY = 'authorization';
const DEFAULT_LOGOUT_WS_PATHNAME = '/logout';

module.exports = {
    DEFAULT_BROWSER_STORAGE_KEY,
    DEFAULT_HTTP_ACCESS_HEADER,
    DEFAULT_URL_ACCESS_PARAM,
    DEFAULT_WS_ACCESS_PARAM,
    DEFAULT_LOGOUT_WS_PATHNAME,
};
